name: Checker

on:
  schedule:
    - cron: '30 */6 * * *'
  workflow_dispatch:

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout public repo
    #   uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install aiohttp

    - name: Clone private repo
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git clone https://x-access-token:${GITHUB_TOKEN}@github.com/SakamichiSeries/news-checker

    - name: Run checker
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: -1001982849593
      run: |
        cd news-checker
        python checker.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        cd news-checker
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add sent.json
        git commit -m "Update sent.json [$(TZ='Asia/Tokyo' date)]" || echo "No changes to commit"
        git push