name: Scraper

on:
  # Runs on pushes targeting the default branch
  schedule:
    - cron: '20 20 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8' # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run scraper
      run: |
        python scraper.py
      working-directory: ./public
    
    - name: Commit changes
      run: |
            git remote set-url origin https://SakamichiSeries:${TOKEN_GITHUB}@github.com/SakamichiSeries/news-archive.git
            git config --global user.email "example@example.com"    
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "Update data" || echo "No changes to commit"
            git push
      env:
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

