name: Scraper

on:
  # Runs on pushes targeting the default branch
  schedule:
    - cron: '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Specify the Python version you need

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run scraper
      run: |
        # TZ='Asia/Tokyo' date
        python download.py
        # TZ='Asia/Tokyo' date
      working-directory: ./public
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_NOGI_CHANNEL: -1001313048085
        TELEGRAM_NEWS_CHANNEL: -1002323394494
        TELEGRAM_HINA_CHANNEL: -1001409510960
        TELEGRAM_SAKU_CHANNEL: -1001230600925
    
    - name: Commit changes
      run: |
            git remote set-url origin https://SakamichiSeries:${PAT}@github.com/SakamichiSeries/news-archive.git
            git config --global user.email "example@example.com"    
            git config --global user.name "GitHub Actions"
            git add .
            git remote -v
            git remote get-url origin
            git commit -m "$(TZ='Asia/Tokyo' date)" || echo "No changes to commit"
            git push
      env:
        PAT: ${{ secrets.PAT }}

  build:
    runs-on: ubuntu-latest
    needs: scraper
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # 使用的 Node.js 版本，可以根据需要更改

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
          path: ./build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
